version: "3"

networks:
    applynow.api-dev:
        driver: bridge

services:
    applynow.api:
        image: applynow.api
        depends_on:
            - "postgres_image"
            - "redis_image"
        build:
            context: "."
            dockerfile: Dockerfile
        ports:
            - "5002:5001"

        links:
            - "redis_image"
        environment:
            DB_CONNECTION_STRING: "host:postgres_image;port=5432;database=applynow;username=admin;password=123456"
        networks:
            - applynow.api-dev


    postgres_image:
        image: postgres:latest
        restart: always
        ports:
            - "5432:5432"
        restart: always
        volumes:
            - db_volume:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "123456"
            POSTGRES_DB: "applynow"
        networks:
            - applynow.api-dev

    redis_image:
        image: redis
        container_name: redis.cache
        ports:
            - "6379:6379"
        networks:
            - applynow.api-dev

volumes:
    db_volume:
